# .streamlit/secrets.toml

[email_credentials]
sender_email = "vivekbisen.vspl@gmail.com"
sender_password = "aaby lrbe lpgl twfp" # Use an App Password for Gmail
smtp_server = "smtp.gmail.com"
smtp_port = 465



[mysql]
host = "localhost"
port = 3306
database = "validation_dashboard_sql"  # <-- THIS IS THE UPDATED NAME
user = "root"
password = "vivekbisen143"     # <-- Use the password you created

